### PR TITLE
Efa 0027 fix efacli logrotate problem

### PR DESCRIPTION
**Pull request by cubitusgh**
See my notes in this thread of the efa support forum:
http://forum.nmichael.de/viewtopic.php?f=15&t=1214&p=4792#p4792

Only efabootshaus will perform a logrotate on startup.
The file size when efabootshaus performs a logrotate is set to 10M.
So efabootshaus will quit logging when the file size exceeds 100M.

Limits of this fix:
WINDOWS
- if another program has an open file handle on the efa.log file (like a log viewer, another efacli instance), efa will copy the log file to the backup directory, but won't be able to delete the current efa.log. So the current efa.log will be used when the logrotate fails. At least, no log entries are lost under windows.
See https://stackoverflow.com/questions/16539233/how-to-check-if-i-can-delete-a-file for a possible solution to determine wether another program has an open file handle on a file (which leads to a failure when attempting to delete the file).

LINUX
- efabootshaus is able to rotate the log file no matter wether another program has an open file handle on the efa.log. This applies to ext3 and ext4 file systems. When efabootshaus rotated the log file whilst it is open by another program B, the new log entries of program B will get lost as they will be discarded after closing the (already deleted) logfile by program B.

A final solution to this problem would be switching to Log4J and configuring it to prudent mode. Or maybe that any efa program logs to its very own log file.

### CODE REVIEW

**Review by nicmichael — CHANGES_REQUESTED** [review]
Thanks for the detailed analysis and description of the issue.

The proposed solution will only have efaBoathouse rotate the logfile, which seems a bit of a workaround rather than a solution, but that's fine. But how about installations which only run a client (efaBase)? For example, I'm running (in a dedicated installation) an efaBase client to access our boathouse. With your changes, its log file will never be rotated.

One solution/hack might be, to force a log file rotation by any client if the log file size has reached 2*MAX_LOG_FILE_SIZE. This should give efaBoathouse plenty of time to do the roation without another client messing with the logfile, but if there's not efaBoathouse running (or it never rotates the log), then have someone else do it.

**Comment by nicmichael** [comment]
@cubitusgh @cubitusgh2 Would it be better if each efa program had its own logfile? Then each program (efa boathouse, efa base, efa cli) could rotate its own logfile without affecting another efa program's logfile.

**Comment by nicmichael** [comment]
Also, it seems you've been rebasing your branch, but haven't updated this PR to address the review comment. Did you forget to push another commit maybe?

**Comment by cubitusgh2** [comment]
Status: I did not work on this PR as I had no good idea concerning your comments.

Currently, on the EFA in my club I run the variant that any EFA program may rotate the logs except EFACLI,
along with the increased limit of 10M for the log file.

This helps with the most pressing issue with lost log file entries due to logrotating attempts by EFACLI.

Another idea could be that efaBoatHouse/efaBase can rotate the log when either the size limit is exceeded, or the log file has entries for more than a day. Then the problem of too big log files would be avoided effectively.

**Comment by cubitusgh2** [comment]
Closing PR as it will get an update soon.
No merge needed for this PR.

**Pull request closed without merging**
